# Directories containing natural image set
natural_dirs: 
  - ''
# Directories containing GAN-generated image set
deepfake_dirs: 
  - ''
# number of top DCT frequencies to include in Benford feature
freq_count: 5
# Train/Test split
test_split: 0.2
# Radix to use for generalized Benford Law pmf
bases:
  - 10
  - 20
# Quantization tables
qtables: 
  - 'PHOTOSHOP_FOR_WEB_100_LUM'
# Images to process per batch for training. 
# Features will be saved in these batch sizes.
# Used for checkpointing and crash recovery during training.
batch_size: 32