# Directory containing natural image set
natural_dir: ''
# Directory containing GAN-generated image set
deepfake_dir: ''
# number of highest DCT frequencies to include in Benford feature
freq_count: 5
# Radix to use for generalized Benford Law pmf
bases:
  - 10
  - 20
# Quantization tables
qtables: 
  - 'PHOTOSHOP_FOR_WEB_100_LUM'
# Images to process per batch for training. 
# Features will be saved in these batch sizes.
# Used for checkpointing and crash recovery during training.
batch_size: 2